#!/usr/bin/env python3
"""
DmAVID Foundry Validator: Compiles and validates adversarial contract variants with PoC tests.

This script takes adversarial contract variants generated by the Red Team Agent and validates
them using Foundry (forge). It compiles variants, runs proof-of-concept exploitation tests,
and records which variants are compilable and successfully exploitable.
"""

import os
import json
import subprocess
import tempfile
import shutil
import re
from pathlib import Path
from datetime import datetime
from typing import Tuple, List, Dict, Any
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# WSL forge PATH
os.environ["PATH"] = "/home/curtis/.foundry/bin:" + os.environ.get("PATH", "")

# Constants
BASE_DIR = os.environ.get("DAVID_BASE_DIR", "/home/curtis/DmAVID")
EXPERIMENTS_DIR = os.path.join(BASE_DIR, "experiments")
RED_TEAM_DIR = os.path.join(EXPERIMENTS_DIR, "red_team")
FOUNDRY_VALIDATION_DIR = os.path.join(EXPERIMENTS_DIR, "foundry_validation")

# Foundry configuration
SOLC_VERSION = "0.8.19"


def check_foundry_installed() -> bool:
    """
    Check if Foundry (forge) is installed and accessible.

    Returns:
        bool: True if forge is found, False otherwise
    """
    try:
        result = subprocess.run(
            ["which", "forge"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            logger.info(f"Foundry found at: {result.stdout.strip()}")
            return True
        else:
            logger.warning("Foundry (forge) not found in PATH")
            print("\n" + "=" * 60)
            print("ERROR: Foundry is not installed")
            print("=" * 60)
            print("Please install Foundry with:")
            print("  curl -L https://foundry.paradigm.xyz | bash")
            print("  foundryup")
            print("=" * 60 + "\n")
            return False
    except Exception as e:
        logger.error(f"Error checking for Foundry: {e}")
        return False


def setup_foundry_project(project_dir: str) -> bool:
    """
    Create a temporary Foundry project structure with basic configuration.

    Args:
        project_dir: Directory path where the Foundry project will be created

    Returns:
        bool: True if setup successful, False otherwise
    """
    try:
        # Create directory structure
        src_dir = os.path.join(project_dir, "src")
        test_dir = os.path.join(project_dir, "test")
        os.makedirs(src_dir, exist_ok=True)
        os.makedirs(test_dir, exist_ok=True)

        # Create foundry.toml configuration
        foundry_config = f"""[profile.default]
solc_version = "{SOLC_VERSION}"
optimizer_runs = 200

[profile.release]
optimizer_runs = 1000

[dependencies]
forge-std = {{ git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.5.2" }}
"""

        foundry_toml_path = os.path.join(project_dir, "foundry.toml")
        with open(foundry_toml_path, 'w') as f:
            f.write(foundry_config)

        logger.debug(f"Foundry project setup at {project_dir}")
        return True
    except Exception as e:
        logger.error(f"Failed to setup Foundry project: {e}")
        return False


def compile_contract(
    contract_source: str,
    project_dir: str,
    offline: bool = False
) -> Tuple[bool, List[str], List[str]]:
    """
    Compile a Solidity contract using Foundry (forge build).

    Args:
        contract_source: Solidity contract source code
        project_dir: Path to the Foundry project directory
        offline: Whether to use --offline flag for forge build

    Returns:
        Tuple of (success: bool, errors: List[str], warnings: List[str])
    """
    try:
        # Write contract to src/Variant.sol
        variant_path = os.path.join(project_dir, "src", "Variant.sol")
        with open(variant_path, 'w') as f:
            f.write(contract_source)

        # Prepare forge build command
        cmd = ["forge", "build"]
        if offline:
            cmd.append("--offline")

        # Run forge build
        result = subprocess.run(
            cmd,
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=60
        )

        errors = []
        warnings = []

        # Parse stderr for errors and warnings
        if result.stderr:
            for line in result.stderr.split('\n'):
                if 'error' in line.lower():
                    errors.append(line.strip())
                elif 'warning' in line.lower():
                    warnings.append(line.strip())

        success = result.returncode == 0

        if success:
            logger.debug("Contract compiled successfully")
        else:
            logger.warning(f"Compilation failed: {result.stderr[:200]}")

        return success, errors, warnings

    except subprocess.TimeoutExpired:
        logger.error("Forge build timeout")
        return False, ["Compilation timeout"], []
    except Exception as e:
        logger.error(f"Compilation error: {e}")
        return False, [str(e)], []


def run_poc_test(
    poc_source: str,
    project_dir: str
) -> Tuple[bool, int, str]:
    """
    Run a proof-of-concept test using Foundry (forge test).

    Args:
        poc_source: Solidity test source code
        project_dir: Path to the Foundry project directory

    Returns:
        Tuple of (passed: bool, gas_used: int, output: str)
    """
    try:
        # Write PoC test to test/ExploitTest.t.sol
        poc_path = os.path.join(project_dir, "test", "ExploitTest.t.sol")
        with open(poc_path, 'w') as f:
            f.write(poc_source)

        # Run forge test with verbose output
        result = subprocess.run(
            ["forge", "test", "-vvv"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=120
        )

        output = result.stdout + result.stderr

        # Parse test results
        passed = result.returncode == 0

        # Extract gas usage if available
        gas_used = 0
        gas_pattern = r'Gas\s+:\s+(\d+)'
        match = re.search(gas_pattern, output)
        if match:
            gas_used = int(match.group(1))

        if passed:
            logger.debug("PoC test passed")
        else:
            logger.warning(f"PoC test failed")

        return passed, gas_used, output

    except subprocess.TimeoutExpired:
        logger.error("Forge test timeout")
        return False, 0, "Test timeout"
    except Exception as e:
        logger.error(f"Test execution error: {e}")
        return False, 0, str(e)


def create_poc_template(contract_name: str = "Variant") -> str:
    """
    Create a basic PoC test template.

    Args:
        contract_name: Name of the contract to test

    Returns:
        str: Solidity test source code template
    """
    poc_template = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Test.sol";
import "../src/Variant.sol";

contract ExploitTest is Test {{
    {contract_name} private target;
    address private attacker = address(0x1234);
    address private victim = address(0x5678);

    function setUp() public {{
        target = new {contract_name}();
    }}

    // Generic test to check if contract is deployable
    function testDeployment() public {{
        assertNotEq(address(target), address(0));
    }}

    // Placeholder for actual vulnerability exploitation
    function testExploit() public {{
        // This test would be populated with actual vulnerability-specific PoC
        assertTrue(true);
    }}
}}
"""
    return poc_template


def validate_variants(variants_file: str, round_num: int = 1) -> Dict[str, Any]:
    """
    Load adversarial variants from Red Team output, compile and test each one.

    Args:
        variants_file: Path to the adversarial variants JSON file
        round_num: Round number for tracking

    Returns:
        Dict containing validation results summary
    """
    logger.info(f"Loading variants from {variants_file}")

    if not os.path.exists(variants_file):
        logger.error(f"Variants file not found: {variants_file}")
        return {
            "error": "Variants file not found",
            "total_variants": 0,
            "compile_success": 0,
            "compile_success_rate": 0.0,
            "poc_success": 0,
            "poc_success_rate": 0.0,
            "valid_variants": 0
        }

    try:
        with open(variants_file, 'r') as f:
            variants_data = json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse variants JSON: {e}")
        return {
            "error": f"JSON parse error: {e}",
            "total_variants": 0,
            "compile_success": 0,
            "compile_success_rate": 0.0,
            "poc_success": 0,
            "poc_success_rate": 0.0,
            "valid_variants": 0
        }

    # Extract variants from different possible JSON structures
    variants = []
    if isinstance(variants_data, dict):
        if "variants" in variants_data:
            variants = variants_data["variants"]
        elif "results" in variants_data:
            variants = variants_data["results"]
        else:
            # Try to extract from top-level items
            for key in variants_data:
                if isinstance(variants_data[key], dict) and "source" in variants_data[key]:
                    variants.append(variants_data[key])
    elif isinstance(variants_data, list):
        variants = variants_data

    logger.info(f"Found {len(variants)} variants to validate")

    validation_results = []
    compile_success_count = 0
    poc_success_count = 0
    valid_count = 0

    # Create temporary Foundry project for all validations
    with tempfile.TemporaryDirectory() as temp_dir:
        if not setup_foundry_project(temp_dir):
            logger.error("Failed to setup Foundry project")
            return {
                "error": "Foundry project setup failed",
                "total_variants": 0,
                "compile_success": 0,
                "compile_success_rate": 0.0,
                "poc_success": 0,
                "poc_success_rate": 0.0,
                "valid_variants": 0
            }

        # Validate each variant
        for idx, variant in enumerate(variants, 1):
            logger.info(f"[{idx}/{len(variants)}] Validating variant...")

            # Extract contract source
            contract_source = variant.get("source") or variant.get("contract_source")
            if not contract_source:
                logger.warning(f"Variant {idx} missing contract source")
                continue

            variant_id = variant.get("id") or variant.get("variant_id") or f"variant_{idx:04d}"

            # Compile the contract
            compile_success, errors, warnings = compile_contract(
                contract_source,
                temp_dir,
                offline=False
            )

            if compile_success:
                compile_success_count += 1
            else:
                logger.warning(f"Variant {variant_id} compilation failed")

            # Run PoC test if compilation succeeded
            poc_passed = False
            gas_used = 0
            poc_output = ""

            if compile_success:
                # Use provided PoC or generate template
                poc_source = variant.get("poc") or variant.get("test_source")
                if not poc_source:
                    # Extract contract name from source (simplified)
                    contract_name = "Variant"
                    name_match = re.search(r'contract\s+(\w+)', contract_source)
                    if name_match:
                        contract_name = name_match.group(1)
                    poc_source = create_poc_template(contract_name)

                poc_passed, gas_used, poc_output = run_poc_test(poc_source, temp_dir)
                if poc_passed:
                    poc_success_count += 1
                    valid_count += 1

            # Record result
            result = {
                "variant_id": variant_id,
                "compile_success": compile_success,
                "compile_errors": errors,
                "compile_warnings": warnings,
                "poc_passed": poc_passed,
                "gas_used": gas_used,
                "vuln_type": variant.get("vuln_type") or variant.get("vulnerability_type", "unknown"),
                "transformation": variant.get("transformation_type", "unknown")
            }
            validation_results.append(result)

            if idx % 5 == 0 or idx == len(variants):
                logger.info(f"  Progress: {compile_success_count} compiled, "
                           f"{poc_success_count} PoCs passed")

    # Calculate metrics
    total_variants = len(variants)
    compile_rate = (compile_success_count / total_variants * 100) if total_variants > 0 else 0
    poc_rate = (poc_success_count / total_variants * 100) if total_variants > 0 else 0
    valid_rate = (valid_count / total_variants * 100) if total_variants > 0 else 0

    summary = {
        "round": round_num,
        "timestamp": datetime.now().isoformat(),
        "total_variants": total_variants,
        "compile_success": compile_success_count,
        "compile_success_rate": round(compile_rate, 2),
        "poc_success": poc_success_count,
        "poc_success_rate": round(poc_rate, 2),
        "valid_variants": valid_count,
        "valid_variants_rate": round(valid_rate, 2),
        "results": validation_results
    }

    return summary


def main():
    """Main execution flow for Foundry validation."""
    print("=" * 70)
    print("DmAVID Foundry Validator: Adversarial Contract Validation")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print("=" * 70)

    # Check if Foundry is installed
    if not check_foundry_installed():
        print("\nFATAL: Foundry is required but not installed. Exiting.")
        return 1

    # Ensure output directory exists
    os.makedirs(FOUNDRY_VALIDATION_DIR, exist_ok=True)

    # Determine which round to process
    round_num = 1
    variants_file = os.path.join(RED_TEAM_DIR, f"adversarial_variants_round_{round_num}.json")

    # Try to find the latest round
    for r in range(1, 10):
        test_file = os.path.join(RED_TEAM_DIR, f"adversarial_variants_round_{r}.json")
        if os.path.exists(test_file):
            round_num = r
            variants_file = test_file

    print(f"\n[*] Processing Round {round_num}")
    print(f"    Variants file: {variants_file}")

    if not os.path.exists(variants_file):
        print(f"\nERROR: No variants file found at {variants_file}")
        print(f"Please run the Red Team Agent first to generate variants.")
        return 1

    # Validate variants
    print("\n[*] Starting variant validation...")
    validation_summary = validate_variants(variants_file, round_num)

    if "error" in validation_summary:
        print(f"\nERROR: {validation_summary['error']}")
        return 1

    # Save results
    output_file = os.path.join(FOUNDRY_VALIDATION_DIR, f"validation_round_{round_num}.json")
    with open(output_file, 'w') as f:
        json.dump(validation_summary, f, indent=2)

    # Print summary
    print("\n" + "=" * 70)
    print("FOUNDRY VALIDATION RESULTS")
    print("=" * 70)
    print(f"Total variants:             {validation_summary['total_variants']}")
    print(f"Compile successful:         {validation_summary['compile_success']} "
          f"({validation_summary['compile_success_rate']:.1f}%)")
    print(f"PoC tests passed:           {validation_summary['poc_success']} "
          f"({validation_summary['poc_success_rate']:.1f}%)")
    print(f"Valid adversarial samples:  {validation_summary['valid_variants']} "
          f"({validation_summary['valid_variants_rate']:.1f}%)")
    print("=" * 70)
    print(f"Results saved to: {output_file}")
    print("=" * 70 + "\n")

    return 0


if __name__ == "__main__":
    exit(main())
